### ISSUE TITLE
What type of data format is required?

### ISSUE THREAD

**Issue by tom68-ll** [songmzhang/NMT-KD#1]
Dear Author,

Could you please explain the data processing workflow in the project? Also, what kind of format is required for the data?

**Comment by songmzhang** [comment]
Hi, you can find the processing workflow of [En-De](https://github.com/facebookresearch/fairseq/blob/main/examples/translation/prepare-wmt14en2de.sh) and [En-Fr](https://github.com/facebookresearch/fairseq/blob/main/examples/translation/prepare-wmt14en2fr.sh) in the examples of fairseq. As for En-Ro, we directly used the processed dataset released by [delight](https://github.com/sacmehta/delight/blob/master/readme_files/nmt/wmt16_en2ro.md).
There is no special requirement for the format of the data. It just needs the binarized parallel sentences (i.e., data-bin) preprocessed from the original dataset like any other translation models in fairseq.

**Comment by tom68-ll** [comment]
Thank you very much for the answer.
